### ISSUE TITLE
add aliases to old posts

### ISSUE THREAD

**Issue by seandavi** [seandavi/seandavi.github.io#1]
* [ ] Posts
* [ ] talks

This was the old configuration:

``` toml
[permalinks]
    talk = "/:year/:month/:day/:slug"
    post = "/:year/:month/:slug"
```

Create aliases as: https://gohugo.io/content-management/urls/#example-aliases

For example:

``` markdown
aliases:
    - /posts/my-original-url/
    - /2010/01/01/even-earlier-url.html
```
